THEMES-1221: Update carousel styles
WPMedia/arc-themes-components pull request #227
Opened 2023-12-08 22:17 UTC by nschubach

## Ticket

- [THEMES-1221](https://arcpublishing.atlassian.net/browse/THEMES-1221)

## Description

Update carousel logical properties

## Acceptance Criteria

The above logical properties are applied and tested on the gallery component.
Storybook is updated with RTL. 

## Test Steps

1. Checkout branch - `git checkout themes-1221`
2. Update dependencies - `npm i`

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed relevant documentation has been updated/added.
- [x] Add label - **ready for review** when the pull request is ready for someone to begin reviewing

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] All GitHub Actions pass
- [ ] Ran the code locally based on the test instructions.
- [ ] Checked Chromatic for Storybook changes, accepted the updates if acceptable
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.
- [ ] Approve and Add label - **ready to merge** if you are happy with the pull request
- [ ] Want another reviewer? Add the label **additional review**

2023-12-12 18:55 UTC, vgalatro requested changes
The changes look good, just noticed some duplicate properties between the `_index.scss` and the `news.json`. The changes are also missing from the `commerce.json`.

Could you add a RTL story to `index.stories.mdx` as well? So we have it whenever we update Storybook.

2023-12-12 18:55 UTC, vgalatro commented on src/components/carousel/_index.scss
> +	max-inline-size: 100cqi;
Are these three props (`container-name`, `container-type`, and `max-inline-size`) supposed to be here? They're also on the token, so they end up appearing twice in the final CSS.

2023-12-13 15:39 UTC, nschubach commented on src/components/carousel/_index.scss
> +	max-inline-size: 100cqi;
```suggestion
	display: grid;
	grid-template-areas: "controls" "carousel" "indicators";
```

2023-12-13 15:40 UTC, nschubach commented on src/components/carousel/_index.scss
> +	max-inline-size: 100cqi;
Nope, I removed these.  I missed moving these over.

2023-12-14 17:53 UTC, vgalatro approved these changes
Changes look good, approved!

2023-12-14 18:34 UTC, merged