TMEDIA-668: date component without formatting
WPMedia/arc-themes-components pull request #28
Opened 2022-02-28 19:57 UTC by JackHowa

Ticket: https://arcpublishing.atlassian.net/jira/software/c/projects/TMEDIA/boards/875?modal=detail&selectedIssue=TMEDIA-668&assignee=5e387d6a1b1d910e5dfd7a9b

# AC

Acceptance Criteria
Create a <Date> component

Using HTML <time> element as output

Required datetime attribute on the element

Input date prop is an ISO format

Input date text is a string

Have Scss file that adds the hooks to the Sass library

Have test coverage

Have storybook documentation

# Test 

1. `npm run storybook`
2. See description along with description of iso 
3. See usages of how the component could work in the docs tab
4.  See two examples of iso 8061 dates shown in the Canvas tab including date and a date and time

# Questions 

- the `<time>` element can take in intervals as well as time on a 24-hour clock. But this didn't seem like part of our usage in the blocks. Do you want me to include examples? 
- I used camelCase for dateTime prop passed in. This seemed in line with react prop naming rather than the html `datetime`
- I used the `dateString` rather than children based on the requirements. This is what we want, right? seems to make sense to me for our current usages

2022-02-28 21:20 UTC, visionbegin requested changes
Looks great Jack!  I do agree with your comment on 24 hour time, I would like to see that and maybe a few more examples expressed in the stories.

2022-03-01 15:31 UTC, JackHowa commented
> Looks great Jack! I do agree with your comment on 24 hour time, I would like to see that and maybe a few more examples expressed in the stories.

good feedback @visionbegin ! I added more examples of datetimes as well

2022-03-01 15:34 UTC, visionbegin approved these changes
Great!

2022-03-01 16:19 UTC, nschubach reviewed
Just have some questions, not rejecting or approving.

2022-03-01 16:19 UTC, nschubach commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
Was there a reason for `dateString` to not be `children`?  We aren't doing anything with it and it's just a "label" so it could potentially be any valid markup.

e: `<time>`'s children can be any [Phrasing Content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content) like potentially an audio clip of the time

2022-03-01 16:19 UTC, nschubach commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
Also, are we considering [schema.org](https://schema.org/Time) (or [this](https://schema.org/DateTime)) microdata for any of these or supporting passthrough of props?

2022-03-01 16:19 UTC, nschubach commented on src/components/date/index.stories.mdx
> +			The concert starts at{" "}
`{" "}` ?

Is this is storybook space enforcement?

2022-03-01 16:20 UTC, JackHowa commented on src/components/date/index.stories.mdx
> +			The concert starts at{" "}
yep

2022-03-01 16:21 UTC, JackHowa commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
that's a good question. in the ticket, there's the assumption that it will be a string `Input date text is a string` https://arcpublishing.atlassian.net/jira/software/c/projects/TMEDIA/boards/875?modal=detail&selectedIssue=TMEDIA-668&assignee=5e387d6a1b1d910e5dfd7a9b

2022-03-01 16:22 UTC, JackHowa commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
huh interesting -- also wow mdn redesign (thought I was on the wrong site for a sec)

2022-03-01 16:29 UTC, merged

2022-03-01 17:06 UTC, matthewroach commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
The reason it's not a chid is that this component will handle the formatting display via a library at some point, and doing that with a child element is not the right way

2022-03-01 19:13 UTC, nschubach commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
@matthewroach I know we were talking about using something like `date-fns` for date things, but the formatted result or the friendly representation of the date passed in would not be parsed any more so than the `children`

If we were referring to the `dateTime` being non-standard or non-parse-able, that would make more sense to me.

2022-03-01 21:18 UTC, matthewroach commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
We would pass in a ISO date format like `2020-02-10T16:08:44.538Z` and a format like `MM YY d, e` the component would handle formatting the display

2022-03-01 21:46 UTC, nschubach commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
Yeah, you pass the ISO date format to the `dateTime` parameter.  You wouldn't pass that to the `dateString`.

The format would have to be a parameter as well, which would determine the `<time>` child.  But this logic would have to be determined whether it overrides the `dateString` or the `children` (whichever was determined) or vice versa ... does the passed in `dateString`/`children` become the friendly representation, or does the library output become the representation?

I guess what I'm saying is that it doesn't matter for the concerns of the library that we look at the `children` or the `dateString` property, but the `children` is a more appropriate location to pass in subordinate elements for the readable layer of this component in cases where the library may not be utilized.

Does that make sense?

2022-03-01 21:51 UTC, matthewroach commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
No exactly - the `dateTime` attribute require different formatting to the output the end user will see. I don't like the idea of the children value being manipulated 

This doesn't make sense to me -
```<Date>2020-02-10T16:08:44.538Z</Date>```


This is how I see it working eventually - 
```<Date dateString="2020-02-10T16:08:44.538Z" format="MM, Y, d, e" dateTime="MM-YY" />```

2022-03-01 22:03 UTC, nschubach commented on src/components/date/index.jsx
> +const Date = ({ className, dateString, dateTime }) => (
`dateTime` is passed directly to the `<time>` element.  This is [by standard required to be a machine readable date value](https://html.spec.whatwg.org/multipage/text-level-semantics.html#attr-time-datetime).  In your example, that becomes a sort of format template?

I see it being something like: 
`<Date dateTime="2020-02-10T16:08:44.538Z" format="MM, Y, d, e" />`
or, if desired:
`<Date dateTime="2023-01-1T00:00:01Z">as the New Year breaks in 2023</Date>`