Git hooks and github actions
WPMedia/arc-themes-components pull request #9
Opened 2022-01-26 22:31 UTC by visionbegin

2022-01-27 11:11 UTC, matthewroach requested changes
The action is failing due to an issue with the `--changedSince` value which I added a comment too

2022-01-27 11:11 UTC, matthewroach commented on package.json
> +    "test:changed-feature-branch": "jest --changedSince=github.head_ref --coverage --passWithNoTests",
This is failing in the action as the value for `--changedSince` needs to be passed via the action like

```npm run test -- --changedSince=${{ github.head_ref }}```

2022-01-28 11:18 UTC, matthewroach commented
@visionbegin - There was some issue with the Chromatic action I rebased from the base branch `arc-themes-release-version-1.19` - you'll need to pull from origin to get the latest updates

Regarding the changed since parameter - I've updated that to work - it needed to be `base_ref` not `head_ref` I made a mistake and got confused between the two keys and what values they provided.

Take a look over the PR and see if it all makes sense now?

2022-01-28 11:18 UTC, matthewroach approved these changes

2022-01-28 11:18 UTC, matthewroach approved these changes

2022-01-28 18:18 UTC, visionbegin commented
> @visionbegin - There was some issue with the Chromatic action I rebased from the base branch `arc-themes-release-version-1.19` - you'll need to pull from origin to get the latest updates
> 
> Regarding the changed since parameter - I've updated that to work - it needed to be `base_ref` not `head_ref` I made a mistake and got confused between the two keys and what values they provided.
> 
> Take a look over the PR and see if it all makes sense now?

@matthewroach Thank you so much for the guidance!

2022-01-28 18:18 UTC, merged